import { useState, useEffect } from 'react';
import { usePermissions } from '../hooks/usePermissions';
import { useAuth } from '../context/AuthContext';

const Settings = () => {
    const { isAdmin } = usePermissions();
    const { user } = useAuth();
    
    const [activeTab, setActiveTab] = useState('general');
    const [saving, setSaving] = useState(false);
    const [savedMsg, setSavedMsg] = useState('');
    
    // Настройки системы
    const [generalSettings, setGeneralSettings] = useState({
        companyName: 'Фитнес-Лайф',
        address: 'г. Москва, ул. Примерная, д. 123',
        phone: '+7 (495) 123-45-67',
        email: 'info@fitness-life.ru',
        workingHours: '06:00 - 23:00',
        timezone: 'Europe/Moscow',
    });
    
    // Настройки уведомлений
    const [notificationSettings, setNotificationSettings] = useState({
        emailNotifications: true,
        smsNotifications: false,
        membershipExpireReminder: 7, // дней до истечения
        trainingReminder: 24, // часов до тренировки
        paymentReminder: true,
    });
    
    // Настройки безопасности
    const [securitySettings, setSecuritySettings] = useState({
        sessionTimeout: 30, // минут
        twoFactorAuth: false,
        passwordMinLength: 8,
        requireSpecialChars: true,
        loginAttempts: 5,
    });
    
    // Настройки отчётов
    const [reportSettings, setReportSettings] = useState({
        defaultReportFormat: 'pdf',
        autoGenerateDaily: false,
        autoGenerateWeekly: true,
        autoGenerateMonthly: true,
        includeCharts: true,
    });

    // Типы занятий (редактируемые)
    const [trainingTypes, setTrainingTypes] = useState([
        { id: 'yoga', name: 'Йога', color: '#9b59b6', active: true },
        { id: 'power', name: 'Силовая', color: '#e74c3c', active: true },
        { id: 'cardio', name: 'Кардио', color: '#3498db', active: true },
        { id: 'personal', name: 'Персональная', color: '#27ae60', active: true },
        { id: 'group', name: 'Групповая', color: '#f39c12', active: true },
        { id: 'swimming', name: 'Плавание', color: '#1abc9c', active: true },
    ]);
    const [newType, setNewType] = useState({ name: '', color: '#4169E1' });

    const handleSave = async () => {
        setSaving(true);
        // Имитация сохранения
        await new Promise(resolve => setTimeout(resolve, 1000));
        setSaving(false);
        setSavedMsg('Настройки сохранены!');
        setTimeout(() => setSavedMsg(''), 3000);
    };

    const addTrainingType = () => {
        if (!newType.name.trim()) return;
        setTrainingTypes([
            ...trainingTypes,
            { id: `custom_${Date.now()}`, ...newType, active: true }
        ]);
        setNewType({ name: '', color: '#4169E1' });
    };

    const toggleTypeActive = (id) => {
        setTrainingTypes(trainingTypes.map(t => 
            t.id === id ? { ...t, active: !t.active } : t
        ));
    };

    const deleteType = (id) => {
        if (!confirm('Удалить тип занятия?')) return;
        setTrainingTypes(trainingTypes.filter(t => t.id !== id));
    };

    const tabs = [
        { id: 'general', icon: '🏢', label: 'Общие' },
        { id: 'notifications', icon: '🔔', label: 'Уведомления' },
        { id: 'training-types', icon: '🏋️', label: 'Типы занятий' },
        { id: 'security', icon: '🔒', label: 'Безопасность' },
        { id: 'reports', icon: '📊', label: 'Отчёты' },
        { id: 'backup', icon: '💾', label: 'Резервные копии' },
    ];

    if (!isAdmin) {
        return (
            <div style={styles.accessDenied}>
                <div style={styles.accessIcon}>🔒</div>
                <h2>Доступ запрещён</h2>
                <p>Только администратор может изменять настройки системы</p>
            </div>
        );
    }

    return (
        <div style={styles.container}>
            {/* Заголовок */}
            <div style={styles.header}>
                <div>
                    <h1 style={styles.title}>Настройки</h1>
                    <p style={styles.subtitle}>
                        Конфигурация системы Фитнес-Менеджер
                    </p>
                </div>
                <button 
                    className="btn btn-primary"
                    onClick={handleSave}
                    disabled={saving}
                >
                    {saving ? '⏳ Сохранение...' : '💾 Сохранить все'}
                </button>
            </div>

            {savedMsg && (
                <div className="alert alert-success" style={{marginBottom: '20px'}}>
                    ✅ {savedMsg}
                </div>
            )}

            <div style={styles.layout}>
                {/* Боковое меню */}
                <div style={styles.sidebar}>
                    {tabs.map(tab => (
                        <button
                            key={tab.id}
                            style={{
                                ...styles.tabBtn,
                                backgroundColor: activeTab === tab.id ? '#4169E1' : 'transparent',
                                color: activeTab === tab.id ? 'white' : '#2c3e50',
                            }}
                            onClick={() => setActiveTab(tab.id)}
                        >
                            <span style={styles.tabIcon}>{tab.icon}</span>
                            {tab.label}
                        </button>
                    ))}
                </div>

                {/* Контент */}
                <div style={styles.content}>
                    {/* Общие настройки */}
                    {activeTab === 'general' && (
                        <div className="card">
                            <h2 style={styles.sectionTitle}>🏢 Общие настройки</h2>
                            <p style={styles.sectionDesc}>Основная информация о фитнес-центре</p>
                            
                            <div className="form-label">Название компании</div>
                            <input
                                className="form-input"
                                value={generalSettings.companyName}
                                onChange={e => setGeneralSettings({...generalSettings, companyName: e.target.value})}
                            />

                            <div className="form-label">Адрес</div>
                            <input
                                className="form-input"
                                value={generalSettings.address}
                                onChange={e => setGeneralSettings({...generalSettings, address: e.target.value})}
                            />

                            <div style={styles.formRow}>
                                <div style={{flex: 1}}>
                                    <div className="form-label">Телефон</div>
                                    <input
                                        className="form-input"
                                        value={generalSettings.phone}
                                        onChange={e => setGeneralSettings({...generalSettings, phone: e.target.value})}
                                    />
                                </div>
                                <div style={{flex: 1}}>
                                    <div className="form-label">Email</div>
                                    <input
                                        className="form-input"
                                        type="email"
                                        value={generalSettings.email}
                                        onChange={e => setGeneralSettings({...generalSettings, email: e.target.value})}
                                    />
                                </div>
                            </div>

                            <div style={styles.formRow}>
                                <div style={{flex: 1}}>
                                    <div className="form-label">Часы работы</div>
                                    <input
                                        className="form-input"
                                        value={generalSettings.workingHours}
                                        onChange={e => setGeneralSettings({...generalSettings, workingHours: e.target.value})}
                                    />
                                </div>
                                <div style={{flex: 1}}>
                                    <div className="form-label">Часовой пояс</div>
                                    <select
                                        className="form-select"
                                        value={generalSettings.timezone}
                                        onChange={e => setGeneralSettings({...generalSettings, timezone: e.target.value})}
                                    >
                                        <option value="Europe/Moscow">Москва (UTC+3)</option>
                                        <option value="Europe/Samara">Самара (UTC+4)</option>
                                        <option value="Asia/Yekaterinburg">Екатеринбург (UTC+5)</option>
                                        <option value="Asia/Novosibirsk">Новосибирск (UTC+7)</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Уведомления */}
                    {activeTab === 'notifications' && (
                        <div className="card">
                            <h2 style={styles.sectionTitle}>🔔 Настройки уведомлений</h2>
                            <p style={styles.sectionDesc}>Управление оповещениями для клиентов и сотрудников</p>
                            
                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Email-уведомления</div>
                                    <div style={styles.settingDesc}>Отправка уведомлений на email клиентов</div>
                                </div>
                                <label style={styles.toggle}>
                                    <input
                                        type="checkbox"
                                        checked={notificationSettings.emailNotifications}
                                        onChange={e => setNotificationSettings({...notificationSettings, emailNotifications: e.target.checked})}
                                    />
                                    <span style={styles.toggleSlider}></span>
                                </label>
                            </div>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>SMS-уведомления</div>
                                    <div style={styles.settingDesc}>Отправка SMS на телефон (платная услуга)</div>
                                </div>
                                <label style={styles.toggle}>
                                    <input
                                        type="checkbox"
                                        checked={notificationSettings.smsNotifications}
                                        onChange={e => setNotificationSettings({...notificationSettings, smsNotifications: e.target.checked})}
                                    />
                                    <span style={styles.toggleSlider}></span>
                                </label>
                            </div>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Напоминание об истечении абонемента</div>
                                    <div style={styles.settingDesc}>За сколько дней уведомлять клиента</div>
                                </div>
                                <select
                                    className="form-select"
                                    style={{width: '120px', marginBottom: 0}}
                                    value={notificationSettings.membershipExpireReminder}
                                    onChange={e => setNotificationSettings({...notificationSettings, membershipExpireReminder: parseInt(e.target.value)})}
                                >
                                    <option value="3">3 дня</option>
                                    <option value="7">7 дней</option>
                                    <option value="14">14 дней</option>
                                    <option value="30">30 дней</option>
                                </select>
                            </div>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Напоминание о тренировке</div>
                                    <div style={styles.settingDesc}>За сколько часов напоминать о занятии</div>
                                </div>
                                <select
                                    className="form-select"
                                    style={{width: '120px', marginBottom: 0}}
                                    value={notificationSettings.trainingReminder}
                                    onChange={e => setNotificationSettings({...notificationSettings, trainingReminder: parseInt(e.target.value)})}
                                >
                                    <option value="1">1 час</option>
                                    <option value="2">2 часа</option>
                                    <option value="24">24 часа</option>
                                    <option value="48">48 часов</option>
                                </select>
                            </div>
                        </div>
                    )}

                    {/* Типы занятий */}
                    {activeTab === 'training-types' && (
                        <div className="card">
                            <h2 style={styles.sectionTitle}>🏋️ Типы занятий</h2>
                            <p style={styles.sectionDesc}>Управление видами тренировок</p>
                            
                            <div style={styles.typesList}>
                                {trainingTypes.map(type => (
                                    <div 
                                        key={type.id} 
                                        style={{
                                            ...styles.typeItem,
                                            opacity: type.active ? 1 : 0.5,
                                        }}
                                    >
                                        <div style={{...styles.typeColor, backgroundColor: type.color}}></div>
                                        <span style={styles.typeName}>{type.name}</span>
                                        <div style={styles.typeActions}>
                                            <button 
                                                className={`btn btn-sm ${type.active ? 'btn-outline' : 'btn-secondary'}`}
                                                onClick={() => toggleTypeActive(type.id)}
                                            >
                                                {type.active ? 'Активен' : 'Выключен'}
                                            </button>
                                            <button 
                                                className="btn btn-sm btn-danger"
                                                onClick={() => deleteType(type.id)}
                                            >
                                                🗑️
                                            </button>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            <div style={styles.addTypeForm}>
                                <input
                                    className="form-input"
                                    placeholder="Название нового типа"
                                    value={newType.name}
                                    onChange={e => setNewType({...newType, name: e.target.value})}
                                    style={{flex: 1, marginBottom: 0}}
                                />
                                <input
                                    type="color"
                                    value={newType.color}
                                    onChange={e => setNewType({...newType, color: e.target.value})}
                                    style={styles.colorPicker}
                                />
                                <button 
                                    className="btn btn-primary"
                                    onClick={addTrainingType}
                                >
                                    + Добавить
                                </button>
                            </div>
                        </div>
                    )}

                    {/* Безопасность */}
                    {activeTab === 'security' && (
                        <div className="card">
                            <h2 style={styles.sectionTitle}>🔒 Безопасность</h2>
                            <p style={styles.sectionDesc}>Настройки безопасности и авторизации</p>
                            
                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Время сессии (минут)</div>
                                    <div style={styles.settingDesc}>Автовыход после бездействия</div>
                                </div>
                                <select
                                    className="form-select"
                                    style={{width: '120px', marginBottom: 0}}
                                    value={securitySettings.sessionTimeout}
                                    onChange={e => setSecuritySettings({...securitySettings, sessionTimeout: parseInt(e.target.value)})}
                                >
                                    <option value="15">15 мин</option>
                                    <option value="30">30 мин</option>
                                    <option value="60">60 мин</option>
                                    <option value="120">2 часа</option>
                                </select>
                            </div>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Двухфакторная аутентификация</div>
                                    <div style={styles.settingDesc}>Дополнительная защита аккаунтов</div>
                                </div>
                                <label style={styles.toggle}>
                                    <input
                                        type="checkbox"
                                        checked={securitySettings.twoFactorAuth}
                                        onChange={e => setSecuritySettings({...securitySettings, twoFactorAuth: e.target.checked})}
                                    />
                                    <span style={styles.toggleSlider}></span>
                                </label>
                            </div>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Минимальная длина пароля</div>
                                    <div style={styles.settingDesc}>Требования к паролю пользователей</div>
                                </div>
                                <select
                                    className="form-select"
                                    style={{width: '120px', marginBottom: 0}}
                                    value={securitySettings.passwordMinLength}
                                    onChange={e => setSecuritySettings({...securitySettings, passwordMinLength: parseInt(e.target.value)})}
                                >
                                    <option value="6">6 символов</option>
                                    <option value="8">8 символов</option>
                                    <option value="10">10 символов</option>
                                    <option value="12">12 символов</option>
                                </select>
                            </div>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Спецсимволы в пароле</div>
                                    <div style={styles.settingDesc}>Требовать !@#$% и т.д.</div>
                                </div>
                                <label style={styles.toggle}>
                                    <input
                                        type="checkbox"
                                        checked={securitySettings.requireSpecialChars}
                                        onChange={e => setSecuritySettings({...securitySettings, requireSpecialChars: e.target.checked})}
                                    />
                                    <span style={styles.toggleSlider}></span>
                                </label>
                            </div>
                        </div>
                    )}

                    {/* Отчёты */}
                    {activeTab === 'reports' && (
                        <div className="card">
                            <h2 style={styles.sectionTitle}>📊 Настройки отчётов</h2>
                            <p style={styles.sectionDesc}>Автоматическая генерация и формат отчётов</p>
                            
                            <div className="form-label">Формат по умолчанию</div>
                            <select
                                className="form-select"
                                value={reportSettings.defaultReportFormat}
                                onChange={e => setReportSettings({...reportSettings, defaultReportFormat: e.target.value})}
                            >
                                <option value="pdf">PDF</option>
                                <option value="excel">Excel</option>
                                <option value="csv">CSV</option>
                            </select>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Ежедневные отчёты</div>
                                    <div style={styles.settingDesc}>Автоматическая генерация каждый день в 23:59</div>
                                </div>
                                <label style={styles.toggle}>
                                    <input
                                        type="checkbox"
                                        checked={reportSettings.autoGenerateDaily}
                                        onChange={e => setReportSettings({...reportSettings, autoGenerateDaily: e.target.checked})}
                                    />
                                    <span style={styles.toggleSlider}></span>
                                </label>
                            </div>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Еженедельные отчёты</div>
                                    <div style={styles.settingDesc}>Автоматическая генерация по воскресеньям</div>
                                </div>
                                <label style={styles.toggle}>
                                    <input
                                        type="checkbox"
                                        checked={reportSettings.autoGenerateWeekly}
                                        onChange={e => setReportSettings({...reportSettings, autoGenerateWeekly: e.target.checked})}
                                    />
                                    <span style={styles.toggleSlider}></span>
                                </label>
                            </div>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Ежемесячные отчёты</div>
                                    <div style={styles.settingDesc}>Автоматическая генерация 1 числа</div>
                                </div>
                                <label style={styles.toggle}>
                                    <input
                                        type="checkbox"
                                        checked={reportSettings.autoGenerateMonthly}
                                        onChange={e => setReportSettings({...reportSettings, autoGenerateMonthly: e.target.checked})}
                                    />
                                    <span style={styles.toggleSlider}></span>
                                </label>
                            </div>

                            <div style={styles.settingRow}>
                                <div>
                                    <div style={styles.settingLabel}>Включать графики</div>
                                    <div style={styles.settingDesc}>Добавлять диаграммы в отчёты</div>
                                </div>
                                <label style={styles.toggle}>
                                    <input
                                        type="checkbox"
                                        checked={reportSettings.includeCharts}
                                        onChange={e => setReportSettings({...reportSettings, includeCharts: e.target.checked})}
                                    />
                                    <span style={styles.toggleSlider}></span>
                                </label>
                            </div>
                        </div>
                    )}

                    {/* Резервные копии */}
                    {activeTab === 'backup' && (
                        <div className="card">
                            <h2 style={styles.sectionTitle}>💾 Резервные копии</h2>
                            <p style={styles.sectionDesc}>Управление резервным копированием данных</p>
                            
                            <div style={styles.backupCard}>
                                <div style={styles.backupIcon}>📦</div>
                                <div style={styles.backupInfo}>
                                    <div style={styles.backupTitle}>Последняя копия</div>
                                    <div style={styles.backupDate}>29 января 2026, 03:00</div>
                                    <div style={styles.backupSize}>Размер: 45.2 MB</div>
                                </div>
                                <button className="btn btn-outline">📥 Скачать</button>
                            </div>

                            <div style={styles.backupActions}>
                                <button className="btn btn-primary btn-lg">
                                    💾 Создать резервную копию
                                </button>
                                <button className="btn btn-outline btn-lg">
                                    📤 Восстановить из файла
                                </button>
                            </div>

                            <div style={styles.backupHistory}>
                                <h3 style={{fontSize: '16px', marginBottom: '12px'}}>История копий</h3>
                                {[
                                    { date: '28 января 2026', size: '44.8 MB' },
                                    { date: '27 января 2026', size: '44.5 MB' },
                                    { date: '26 января 2026', size: '44.1 MB' },
                                ].map((backup, i) => (
                                    <div key={i} style={styles.backupHistoryItem}>
                                        <span>📁 {backup.date}</span>
                                        <span style={{color: '#7f8c8d'}}>{backup.size}</span>
                                        <button className="btn btn-sm btn-outline">Скачать</button>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

const styles = {
    container: {
        padding: '10px',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '24px',
    },
    title: {
        fontSize: '28px',
        fontWeight: '700',
        color: '#2c3e50',
        margin: 0,
    },
    subtitle: {
        fontSize: '14px',
        color: '#7f8c8d',
        margin: '4px 0 0',
    },
    layout: {
        display: 'flex',
        gap: '24px',
    },
    sidebar: {
        width: '220px',
        flexShrink: 0,
    },
    tabBtn: {
        width: '100%',
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '12px 16px',
        border: 'none',
        borderRadius: '8px',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
        marginBottom: '4px',
        transition: 'all 0.2s',
        textAlign: 'left',
    },
    tabIcon: {
        fontSize: '18px',
    },
    content: {
        flex: 1,
    },
    sectionTitle: {
        fontSize: '20px',
        fontWeight: '600',
        color: '#2c3e50',
        marginBottom: '8px',
    },
    sectionDesc: {
        color: '#7f8c8d',
        marginBottom: '24px',
    },
    formRow: {
        display: 'flex',
        gap: '16px',
    },
    settingRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '16px 0',
        borderBottom: '1px solid #f0f0f0',
    },
    settingLabel: {
        fontWeight: '600',
        color: '#2c3e50',
        marginBottom: '4px',
    },
    settingDesc: {
        fontSize: '13px',
        color: '#7f8c8d',
    },
    toggle: {
        position: 'relative',
        display: 'inline-block',
        width: '50px',
        height: '28px',
    },
    toggleSlider: {
        position: 'absolute',
        cursor: 'pointer',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: '#ccc',
        borderRadius: '28px',
        transition: '0.3s',
    },
    typesList: {
        marginBottom: '20px',
    },
    typeItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '12px',
        background: '#f8f9fa',
        borderRadius: '8px',
        marginBottom: '8px',
    },
    typeColor: {
        width: '24px',
        height: '24px',
        borderRadius: '6px',
    },
    typeName: {
        flex: 1,
        fontWeight: '500',
    },
    typeActions: {
        display: 'flex',
        gap: '8px',
    },
    addTypeForm: {
        display: 'flex',
        gap: '12px',
        alignItems: 'center',
        padding: '16px',
        background: '#f8f9fa',
        borderRadius: '8px',
    },
    colorPicker: {
        width: '50px',
        height: '40px',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
    },
    backupCard: {
        display: 'flex',
        alignItems: 'center',
        gap: '20px',
        padding: '20px',
        background: '#f8f9fa',
        borderRadius: '12px',
        marginBottom: '20px',
    },
    backupIcon: {
        fontSize: '40px',
    },
    backupInfo: {
        flex: 1,
    },
    backupTitle: {
        fontWeight: '600',
        marginBottom: '4px',
    },
    backupDate: {
        color: '#27ae60',
        fontSize: '14px',
    },
    backupSize: {
        color: '#7f8c8d',
        fontSize: '13px',
    },
    backupActions: {
        display: 'flex',
        gap: '12px',
        marginBottom: '24px',
    },
    backupHistory: {
        background: '#f8f9fa',
        borderRadius: '12px',
        padding: '16px',
    },
    backupHistoryItem: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '12px 0',
        borderBottom: '1px solid #e0e4e8',
    },
    accessDenied: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '60vh',
        textAlign: 'center',
        color: '#7f8c8d',
    },
    accessIcon: {
        fontSize: '64px',
        marginBottom: '16px',
    },
};

// CSS для toggle switch
const styleSheet = document.createElement('style');
styleSheet.textContent = `
    .toggle input {
        opacity: 0;
        width: 0;
        height: 0;
    }
    .toggle input:checked + span {
        background-color: #4169E1;
    }
    .toggle input:checked + span:before {
        transform: translateX(22px);
    }
    .toggle span:before {
        position: absolute;
        content: "";
        height: 20px;
        width: 20px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        border-radius: 50%;
        transition: 0.3s;
    }
`;
document.head.appendChild(styleSheet);

export default Settings;